name: main
on: [push]
jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git setup
        id: git-setup
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "WORKDIR=$(pwd)" >> $GITHUB_ENV

      - name: conda env
        run: |
          eval "$(conda shell.bash hook)"
          conda create -y -p ./env \
            --channel conda-forge \
            --channel bioconda \
            python=${{ matrix.python-version }} \
            --file requirements.txt

          conda activate ./env
          rm -rf dist
          python setup.py sdist
          (cd dist && pip install gffutils-*.tar.gz)
          cd $TMPDIR
          python -c "import gffutils; print(gffutils.__file__)"
          conda deactivate

          # TODO: run nosetests that exclude tests requiring optional packages

      - name: run unit tests
        run: |
          eval "$(conda shell.bash hook)"
          conda install -y -p ./env \
            --channel conda-forge \
            --channel bioconda \
            --file optional-requirements.txt \
            nose

          conda activate ./env
          nosetests -v --with-doctest -a '!slow'
          conda deactivate

      - name: doctests
        run: |
          eval "$(conda shell.bash hook)"
          conda install -y -p ./env \
            --channel conda-forge \
            --channel bioconda \
            sphinx make
          conda activate ./env
          (cd docs && make clean doctest)
          conda deactivate


